[feat] 유저 닉네임 중복 방지
LeagueOfFandom/lof-server pull request #1
Opened 2022-10-12 09:34 UTC by summit45

2022-10-12 09:51 UTC, imygnam requested changes

2022-10-12 09:51 UTC, imygnam commented on src/main/java/com/lof/lofserver/domain/user/UserRepository.java
> +    List<UserEntity> findByNickname(String nickname);
List 가 아닌 UserEnity 로 뽑아야 할 것 같습니다.(db 에도 unique 적용 필요)

2022-10-12 09:51 UTC, imygnam commented on src/main/java/com/lof/lofserver/exception/ErrorResponseDto.java
> +@AllArgsConstructor
기존 dto 들이 record 여서 통일하면 좋을듯 합니다.

2022-10-12 09:51 UTC, imygnam commented on src/test/java/com/lof/lofserver/service/user/UserServiceImplTest.java
> +        //when
then을 쪼개서 when에 넣으면 좋을듯 합니다

2022-10-17 08:51 UTC, summit45 commented on src/main/java/com/lof/lofserver/domain/user/UserRepository.java
> +    List<UserEntity> findByNickname(String nickname);
적용 완료

2022-10-17 08:51 UTC, summit45 commented on src/main/java/com/lof/lofserver/exception/ErrorResponseDto.java
> +@AllArgsConstructor
record로 변경완료

2022-10-17 08:52 UTC, summit45 commented on src/test/java/com/lof/lofserver/service/user/UserServiceImplTest.java
> +        //when
테스트 코드 수정

2022-10-17 08:52 UTC, summit45 commented on src/test/java/com/lof/lofserver/service/user/UserServiceImplTest.java
> +        //when
테스트 코드 수정

2022-10-17 15:16 UTC, imygnam approved these changes
수고하셨습니다. pr의 경우 메일로 오는 것으로 확인을 하는데 저녁이후는 메일 알람이 꺼져있어서 카톡으로 알려주면 감사하겠습니다.

2022-10-17 15:16 UTC, imygnam commented on src/main/java/com/lof/lofserver/domain/user/UserRepository.java
> +    Optional<UserEntity> findByNickname(String nickname);
optional 일 필요 없는 것으로 알고 있습니다.

2022-10-17 15:16 UTC, imygnam commented on src/main/java/com/lof/lofserver/service/user/UserServiceImpl.java
> +        Optional<UserEntity> optionalUser = userRepository.findByNickname(nickname);
userRpository.findByNickame.orElse 로 바로 throw 하는게 가능. (한줄로 가능)

2022-10-18 04:23 UTC, merged